name: rota_mercado_livre
description: Aplicativo para gerenciar rotas de entrega do Mercado Livre.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  month_picker_dialog: ^6.7.1
  mongo_dart: ^0.10.8
  http: ^1.6.0
  google_fonts: ^6.1.0
  file_picker: ^8.0.3
  syncfusion_flutter_pdf: ^32.2.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/app_icon.png

flutter:
  uses-material-design: true
